events {
    worker_connections 1024;
}

http {
    include       /opt/homebrew/etc/nginx/mime.types;
    default_type  application/octet-stream;

    # 1. Ограничение частоты запросов (Rate Limiting)
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=1r/s;

    # 2. Балансировка бэкендов (Upstream)
    upstream backend_servers {
        server 127.0.0.1:8000;
        server 127.0.0.1:8001;
    }


    # Виртуальный хост 1: Основной приют (localhost)
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri; # Редирект с HTTP на HTTPS
    }

    server {
        listen 443 ssl;
        server_name localhost;

        # Подключение сгенерированных SSL-сертификатов 
        ssl_certificate      /Users/nasta/Documents/ProgrammingWeb/tamagotchi-shelter/ssl/nginx.crt;
        ssl_certificate_key  /Users/nasta/Documents/ProgrammingWeb/tamagotchi-shelter/ssl/nginx.key;

        ssl_protocols        TLSv1.2 TLSv1.3;
        ssl_ciphers          HIGH:!aNULL:!MD5;


        error_page 404 /404.html;
        location = /404.html {
            root /Users/nasta/Documents/ProgrammingWeb/tamagotchi-shelter/frontend;
            internal;
        }


        # Раздача статики фронтенда
        location / {
            root /Users/nasta/Documents/ProgrammingWeb/tamagotchi-shelter/frontend;
            index index.html;
        }

        # Использование alias для документов (/docs -> info.txt)
        location /docs {
            alias /Users/nasta/Documents/ProgrammingWeb/tamagotchi-shelter/docs/;
            index info.txt;
            charset utf-8;
        }

        # Проксирование API с балансировкой
        location /api/ {
            limit_req zone=api_limit burst=2 nodelay;
            limit_req_status 429;
            error_page 429 = @too_many_requests;

            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location @too_many_requests {
            return 429 "Слишком много запросов!\n";
            add_header Content-Type "text/plain; charset=utf-8";
            charset utf-8;
        }

        # Закрытая зона админки
        location /admin {
            auth_basic "Доступ только для администраторов приюта";
            auth_basic_user_file /Users/nasta/Documents/ProgrammingWeb/tamagotchi-shelter/auth/htpasswd;
            alias /Users/nasta/Documents/ProgrammingWeb/tamagotchi-shelter/docs/;
            
            try_files /admin.txt =404;
            charset utf-8;
        }
    }


    # Виртуальный хост 2: Чужой сайт (fake.local)
    server {
        listen 80;
        server_name fake.local;

        location / {
            root /Users/nasta/Documents/ProgrammingWeb/tamagotchi-shelter/fake_site;
            index index.html;
        }
    }
}
